EXTENSION = sessionbound_guard
MODULE_big = sessionbound_guard
OBJS = sessionbound_guard.o
DATA = sessionbound_guard--0.1.sql

PG_CONFIG ?= pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
